version: 2.1
jobs:
  build:
    docker:
      - image: apline:3.15
    steps:
      - run: echo 'Hello from Build!'

  deploy:
    docker:
      - image: alpine:3.15
    steps:
      - run: echo 'Hello from Deploy'

workflows:
  version: 2
  build_and_deploy:
    Jobs:
      - build
      - deploy


